import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

test('live discovered buyers, indexed search, sourced profile and accessible discovery', async ({ page }) => {
  const password = readFileSync(new URL('../../.env', import.meta.url), 'utf8').split('\n')
    .find(line => line.startsWith('ADMIN_PASSWORD='))?.slice('ADMIN_PASSWORD='.length)
  if (!password) throw new Error('Local ADMIN_PASSWORD is required')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('link', { name: 'Buyers', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Buyers', exact: true })).toBeVisible()
  const summary = await (await page.request.get('/api/buyers/summary')).json()
  expect(summary.total).toBeGreaterThan(0)
  for (const country of ['DK', 'FI', 'IS', 'NO', 'SE', 'CH', 'DE']) expect(summary.by_country[country]).toBeGreaterThan(0)
  expect(await page.locator('.sidebar__mark').evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBeTruthy()
  await page.getByLabel('Filter buyers by country').selectOption('CH')
  await expect(page.locator('tbody tr').first()).toContainText('CH')
  await page.getByLabel('Filter buyers by country').selectOption('')

  const profiles = await (await page.request.get('/api/buyers?status=profiled&limit=1')).json()
  expect(profiles.items.length).toBeGreaterThan(0)
  const buyer = profiles.items[0]
  await page.getByPlaceholder('Search by name, strategy or sector').fill(buyer.name)
  await page.getByRole('link', { name: buyer.name, exact: true }).click()
  await expect(page.getByRole('heading', { name: buyer.name, exact: true })).toBeVisible()
  const detail = await (await page.request.get(`/api/buyers/${buyer.id}`)).json()
  expect(detail.facts.length).toBeGreaterThan(0)
  expect(detail.facts.every((fact: { excerpt: string; source_url: string }) => fact.excerpt && fact.source_url)).toBeTruthy()
  await expect(page.getByRole('heading', { name: 'Facts & excerpts', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Open source', exact: true }).first()).toBeVisible()
  await page.screenshot({ path: '../data/screenshots/buyer-profile.png', fullPage: true })

  await page.getByRole('link', { name: 'Buyers', exact: true }).first().click()
  await page.getByRole('button', { name: 'Discovery', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Buyer discovery' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('checkbox')).toHaveCount(7)
  for (let i = 0; i < 12; i++) await page.keyboard.press('Tab')
  expect(await page.evaluate(() => Boolean(document.activeElement?.closest('dialog')))).toBeTruthy()
  await page.screenshot({ path: '../data/screenshots/buyer-discovery.png', fullPage: true })
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Discovery', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Add buyer', exact: true }).click()
  await expect(page.getByLabel('Website', { exact: true })).toHaveAttribute('required', '')
  await expect(page.getByLabel('Region', { exact: true })).toHaveAttribute('required', '')
  await page.keyboard.press('Escape')
  await page.screenshot({ path: '../data/screenshots/buyers.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  expect(errors).toEqual([])
})
