import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

test('country discovery, paging and responsive navigation use the populated database', async ({ page }) => {
  test.skip(process.env.RUN_REGISTRY_E2E !== '1', 'Requires at least 100 imported Swiss companies')
  const password = readFileSync('../.env', 'utf8').split('\n').find(line => line.startsWith('ADMIN_PASSWORD='))?.slice(15)
  const login = await page.request.post('/api/auth/login', { data: { password } })
  expect(login.ok()).toBeTruthy()
  await page.goto('/companies')
  await page.getByLabel('Filter companies by country').selectOption('CH')
  await expect(page.locator('.company-table tbody tr')).toHaveCount(50)
  await expect(page.locator('.company-table tbody tr').first().locator('td').nth(1)).toHaveText('CH')
  const next = page.waitForResponse(r => r.url().includes('offset=50') && r.url().includes('country=CH'))
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  expect((await next).ok()).toBeTruthy()
  await expect(page.getByRole('navigation', { name: 'Company pages' })).toContainText('51–100')
  await page.getByText('Discover and research companies', { exact: true }).click()
  for (const country of ['Finland', 'Switzerland', 'Germany']) await expect(page.locator('.registry-country').filter({ has: page.getByRole('heading', { name: country, exact: true }) })).toBeVisible()
  await expect(page.locator('.registry-country').filter({ hasText: 'Germany' })).toContainText('subset')
  await page.screenshot({ path: '../data/screenshots/discovery-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy()
  await page.screenshot({ path: '../data/screenshots/discovery-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Assistant', exact: true }).click()
  await expect(page.getByLabel('Message the assistant')).toBeFocused()
  await page.getByLabel('Message the assistant').fill('Draft stays here')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Assistant', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Assistant', exact: true }).click()
  await expect(page.getByLabel('Message the assistant')).toHaveValue('Draft stays here')
})
