import { test, expect } from '@playwright/test'

const company = { id: 'seller', name: 'Research Seller', country: 'FI', status: 'provisional', identifiers: [] }
const scenarios = ['Sell the whole company', 'Keep a 25% stake', 'Keep the team in place'].map((label, index) => ({ id: String(index), label, hypothetical: true, status: 'research_needed', checks: [{ origin: 'owner', key: 'structure', result: 'unknown', detail: 'mandate is silent on max_rollover_pct' }], questions: ['Confirm buyer terms'] }))
const run = { id: 'run-1', company_id: 'seller', company_name: company.name, created_at: '2026-09-27T12:00:00Z', buyers_evaluated: 20, buyers_not_evaluated: 3, rejected_recommendations: 0, scope: 'Sourced buyers', limitations: ['No confirmed interest'], results: [{ buyer_id: 'buyer', buyer_name: 'Research Buyer', reason: 'Both published sources discuss industrial software.', interpretation: 'Exploratory interpretation', status: 'research_needed', sources: [{ ref: 'E1', title: 'Buyer strategy', url: 'https://example.org/strategy', field: 'buyer_sector', value: 'Industrial software', excerpt: 'We invest in industrial software.', review_status: 'proposed', retrieved_at: null }], questions: ['Confirm owner interest'], scenarios, decision_tree: [{ question: 'Is the owner open to a sale?', state: 'unknown', yes: 'Review terms', no: 'Stop: no outreach', unknown: 'Ask the owner' }] }] }

test('a novice runs all scenarios in one action, sees sources and explores the tree', async ({ page }) => {
  await page.route('**/api/auth/me', route => route.fulfill({ json: { authenticated: true, csrf_token: 'test' } }))
  await page.route('**/api/assistant/conversations', route => route.fulfill({ json: [] }))
  await page.route('**/api/companies**', route => route.fulfill({ json: route.request().url().includes('/seller') ? company : { items: [company], total: 1 } }))
  await page.route('**/api/simulations/options', route => route.fulfill({ json: { companies: [company], scenarios } }))
  await page.route('**/api/simulations', route => route.fulfill({ json: route.request().method() === 'POST' ? run : [] }))
  await page.goto('/matches')
  await expect(page.getByRole('heading', { name: 'Future simulations', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Simulation workflow' })).toContainText('Ready to explore')
  await expect(page.getByRole('button', { name: 'Explore futures', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: /Research Seller/ }).click()
  await page.getByRole('button', { name: 'Explore futures', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Possible futures for Research Seller' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Simulation workflow' })).toContainText('Results saved')
  await expect(page.getByRole('region', { name: 'Simulation workflow' })).toContainText('20 profiles evaluated')
  await expect(page.getByRole('link', { name: 'Buyer strategy' })).toHaveAttribute('href', 'https://example.org/strategy')
  await page.getByRole('button', { name: /Keep a 25% stake/ }).click()
  await expect(page.getByText('Keep a 25% stake — hypothetical')).toBeVisible()
  await expect(page.locator('.future-sim__branch-detail')).toContainText('how much equity the owner can retain')
  await page.getByText('View the full decision tree').click()
  await expect(page.getByText('Stop: no outreach')).toBeVisible()
  await expect(page.getByText('20 sourced profiles compared', { exact: false })).toBeVisible()
  await page.screenshot({ path: '../data/screenshots/future-simulations.png', fullPage: true })
})

test('missing research gives an actionable error instead of a fake match', async ({ page }) => {
  await page.route('**/api/auth/me', route => route.fulfill({ json: { authenticated: true, csrf_token: 'test' } }))
  await page.route('**/api/assistant/conversations', route => route.fulfill({ json: [] }))
  await page.route('**/api/companies**', route => route.fulfill({ json: { items: [company], total: 1 } }))
  await page.route('**/api/simulations/options', route => route.fulfill({ json: { companies: [company], scenarios } }))
  await page.route('**/api/simulations', route => route.request().method() === 'POST' ? route.fulfill({ status: 409, json: { error: { code: 'seller_research_needed', message: 'Research this company first.' } } }) : route.fulfill({ json: [] }))
  await page.goto('/matches')
  await page.getByRole('button', { name: /Research Seller/ }).click()
  await page.getByRole('button', { name: 'Explore futures', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Research this company first.')
  await expect(page.getByRole('link', { name: 'Review company research' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Explore futures', exact: true })).toBeEnabled()
  await expect(page.getByRole('region', { name: 'Simulation workflow' })).toContainText('Run needs attention')
})

test('saved real-data simulation opens with its sources and decision branches', async ({ page }) => {
  test.skip(process.env.RUN_SIMULATION_LIVE_E2E !== '1', 'Uses existing local simulation results')
  const { readFileSync } = await import('node:fs')
  const password = readFileSync('../.env', 'utf8').split('\n').find(line => line.startsWith('ADMIN_PASSWORD='))?.slice('ADMIN_PASSWORD='.length)
  if (!password) throw new Error('Local operator password is required')
  await page.goto('/matches')
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Future simulations', exact: true })).toBeVisible()
  const response = await page.request.get('/api/simulations')
  expect(response.ok()).toBeTruthy()
  const saved = await response.json()
  const selected = saved.find((item: { company_name: string; lead_count: number }) => item.company_name === 'Revendex Solutions GmbH' && item.lead_count > 0)
  expect(selected).toBeTruthy()
  await page.goto(`/matches?run=${selected.id}`)
  await expect(page.getByRole('heading', { name: 'Possible futures for Revendex Solutions GmbH' })).toBeVisible()
  await expect(page.locator('.future-sim__evidence a').first()).toHaveAttribute('href', /^https?:\/\//)
  await page.getByText('View the full decision tree', { exact: true }).first().click()
  await expect(page.getByText('Stop: no outreach').first()).toBeVisible()
  await page.screenshot({ path: '../data/screenshots/future-simulations-live.png', fullPage: true })
})
